/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms. */

function fiboEvenSum(n) {
  let a=1;
  let b=2;
  let sum=0;
  while (b<=n)
  {
    if (b%2===0)
    {
      sum+=b
    }
    let next=a+b;
    a=b;
    b=next
  }
  return sum
}
console.log(fiboEvenSum(8))